name: Upload C API Binaries
on:
  push:
    tags:
      - '*'
jobs:
  c-api-binary-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cbindgen
        run: |
          cargo install cbindgen
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Set Environment Variables
        run: |
          QISKIT_CEXT_VERSION=$(
            cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select( .name == "qiskit-cext" ).version'
          )
          QISKIT_CEXT_DIR="qiskit-cext-${QISKIT_CEXT_VERSION}-linux-amd64"

          echo "QISKIT_CEXT_VERSION=$QISKIT_CEXT_VERSION" >> $GITHUB_ENV
          echo "QISKIT_CEXT_DIR=${QISKIT_CEXT_DIR}" >> $GITHUB_ENV
      - name: Build Binary
        run: |
          mkdir -p ${{ env.QISKIT_CEXT_DIR }}/dist/c/lib
          cargo rustc --release --crate-type cdylib -p qiskit-cext
          cp target/release/libqiskit_cext.so ${{ env.QISKIT_CEXT_DIR }}/dist/c/lib/libqiskit.so
          mkdir -p ${{ env.QISKIT_CEXT_DIR }}/dist/c/include
          mkdir ${{ env.QISKIT_CEXT_DIR }}/dist/c/include/qiskit
          cp target/qiskit.h ${{ env.QISKIT_CEXT_DIR }}/dist/c/include/qiskit.h
          cp crates/cext/include/complex.h ${{ env.QISKIT_CEXT_DIR }}/dist/c/include/qiskit/complex.h
      - name: Archive Binaries
        run: |
          tar czf ${{ env.QISKIT_CEXT_DIR }}.tar.gz ${{ env.QISKIT_CEXT_DIR }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.QISKIT_CEXT_DIR }}.tar.gz
          fail_on_unmatched_files: true
  c-api-binary-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cbindgen
        run: |
          cargo install cbindgen
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Set Environment Variables
        run: |
          QISKIT_CEXT_VERSION=$(
            cargo metadata --format-version=1 --no-deps | jq -r '.packages[] | select( .name == "qiskit-cext" ).version'
          )
          QISKIT_CEXT_DIR="qiskit-c-${QISKIT_CEXT_VERSION}-macos-arm64"

          echo "QISKIT_CEXT_VERSION=$QISKIT_CEXT_VERSION" >> $GITHUB_ENV
          echo "QISKIT_CEXT_DIR=${QISKIT_CEXT_DIR}" >> $GITHUB_ENV
      - name: Build Binary
        run: |
          mkdir -p ${{ env.QISKIT_CEXT_DIR }}/dist/c/lib
          cargo rustc --release --crate-type cdylib -p qiskit-cext
          cp target/release/libqiskit_cext.dylib ${{ env.QISKIT_CEXT_DIR }}/dist/c/lib/libqiskit.dylib
          mkdir -p ${{ env.QISKIT_CEXT_DIR }}/dist/c/include
          mkdir ${{ env.QISKIT_CEXT_DIR }}/dist/c/include/qiskit
          cp target/qiskit.h ${{ env.QISKIT_CEXT_DIR }}/dist/c/include/qiskit.h
          cp crates/cext/include/complex.h ${{ env.QISKIT_CEXT_DIR }}/dist/c/include/qiskit/complex.h
      - name: Archive Binaries
        run: |
          tar czf ${{ env.QISKIT_CEXT_DIR }}.tar.gz ${{ env.QISKIT_CEXT_DIR }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.QISKIT_CEXT_DIR }}.tar.gz
          fail_on_unmatched_files: true
